# This is default comment 

configuration:  
  projectName: configclient
server:
  port: 8000
message:
  greeting: Hello from the configuration, This is my Demo!, There is some change in Config
